name: validations

on:
  pull_request:
    branches: [main]

jobs:
  validations:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - shell: bash
        run: echo -e '/// <reference types="next" />\n/// <reference types="next/image-types/global" />' > next-env.d.ts

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run eslint

      - name: Run Prettier Check
        run: npm run format

      - name: Run Types Check
        run: npm run tsc
